export interface BlockDef {
  id: string;
  index: number;
  color: string;
  name: string;
  isWater: boolean;
}

export const BLOCKS: BlockDef[] = [
  { id: 'air', index: 0, color: 'transparent', name: 'Air', isWater: false },
  { id: 'grass', index: 201, color: '#3b82f6', name: 'Grass', isWater: false },
  { id: 'oak_wood', index: 1, color: '#4A8DB4', name: 'Oak wood', isWater: false },
  { id: 'pine_wood', index: 2, color: '#FFBB3D', name: 'Pine wood', isWater: false },
  { id: 'birch_wood', index: 3, color: '#C24E3D', name: 'Birch wood', isWater: false },
  { id: 'maple_wood', index: 4, color: '#FDE438', name: 'Maple wood', isWater: false },
  { id: 'spruce_wood', index: 5, color: '#077A2B', name: 'Spruce wood', isWater: false },
  { id: 'ash_wood', index: 6, color: '#0BBA37', name: 'Ash wood', isWater: false },
  { id: 'mahogany_wood', index: 7, color: '#B6826D', name: 'Mahogany wood', isWater: false },
  { id: 'cedar_wood', index: 8, color: '#ED8EDA', name: 'Cedar wood', isWater: false },
  { id: 'willow_branch', index: 9, color: '#A9B728', name: 'Willow branch', isWater: false },
  { id: 'yew_wood', index: 10, color: '#2962E2', name: 'Yew wood', isWater: false },
  { id: 'bamboo', index: 11, color: '#29CB14', name: 'Bamboo', isWater: false },
  { id: 'driftwood', index: 12, color: '#8A81B6', name: 'Driftwood', isWater: false },
  { id: 'tree_bark', index: 13, color: '#DA35DA', name: 'Tree bark', isWater: false },
  { id: 'pinecone', index: 14, color: '#3F5CB3', name: 'Pinecone', isWater: false },
  { id: 'acorn', index: 15, color: '#C2A769', name: 'Acorn', isWater: false },
  { id: 'wood_sap', index: 16, color: '#55540F', name: 'Wood sap', isWater: false },
  { id: 'pine_resin', index: 17, color: '#ACBB35', name: 'Pine resin', isWater: false },
  { id: 'rubber_latex', index: 18, color: '#D46442', name: 'Rubber latex', isWater: false },
  { id: 'cork', index: 19, color: '#2023C5', name: 'Cork', isWater: false },
  { id: 'palm_frond', index: 20, color: '#5583CB', name: 'Palm frond', isWater: false },
  { id: 'granite', index: 21, color: '#ED6722', name: 'Granite', isWater: false },
  { id: 'basalt', index: 22, color: '#2C8135', name: 'Basalt', isWater: false },
  { id: 'limestone', index: 23, color: '#980590', name: 'Limestone', isWater: false },
  { id: 'sandstone', index: 24, color: '#9F0A41', name: 'Sandstone', isWater: false },
  { id: 'slate', index: 25, color: '#C43179', name: 'Slate', isWater: false },
  { id: 'marble', index: 26, color: '#F15F5D', name: 'Marble', isWater: false },
  { id: 'obsidian', index: 27, color: '#D3867B', name: 'Obsidian', isWater: false },
  { id: 'flint', index: 28, color: '#0D1D49', name: 'Flint', isWater: false },
  { id: 'quartz', index: 29, color: '#D71ABB', name: 'Quartz', isWater: false },
  { id: 'shale', index: 30, color: '#C25F05', name: 'Shale', isWater: false },
  { id: 'pumice', index: 31, color: '#2792A3', name: 'Pumice', isWater: false },
  { id: 'chalk', index: 32, color: '#E0E6FB', name: 'Chalk', isWater: false },
  { id: 'river_rock', index: 33, color: '#B8B919', name: 'River rock', isWater: false },
  { id: 'gravel', index: 34, color: '#9C6B27', name: 'Gravel', isWater: false },
  { id: 'geode', index: 35, color: '#181B72', name: 'Geode', isWater: false },
  { id: 'talc', index: 36, color: '#27A8C4', name: 'Talc', isWater: false },
  { id: 'gypsum', index: 37, color: '#05D7ED', name: 'Gypsum', isWater: false },
  { id: 'mica', index: 38, color: '#24971A', name: 'Mica', isWater: false },
  { id: 'jade', index: 39, color: '#231C18', name: 'Jade', isWater: false },
  { id: 'amethyst', index: 40, color: '#20D7AD', name: 'Amethyst', isWater: false },
  { id: 'iron_ore', index: 41, color: '#446FAA', name: 'Iron ore', isWater: false },
  { id: 'copper_ore', index: 42, color: '#D2737B', name: 'Copper ore', isWater: false },
  { id: 'tin_ore', index: 43, color: '#D69EBB', name: 'Tin ore', isWater: false },
  { id: 'zinc_ore', index: 44, color: '#D07A06', name: 'Zinc ore', isWater: false },
  { id: 'lead_ore', index: 45, color: '#C6303E', name: 'Lead ore', isWater: false },
  { id: 'silver_ore', index: 46, color: '#AF9B6F', name: 'Silver ore', isWater: false },
  { id: 'gold_ore', index: 47, color: '#23EF42', name: 'Gold ore', isWater: false },
  { id: 'platinum_ore', index: 48, color: '#D55B0E', name: 'Platinum ore', isWater: false },
  { id: 'bauxite_aluminum_ore', index: 49, color: '#B81C67', name: 'Bauxite (Aluminum ore)', isWater: false },
  { id: 'nickel_ore', index: 50, color: '#1CB92C', name: 'Nickel ore', isWater: false },
  { id: 'cobalt_ore', index: 51, color: '#12A1D5', name: 'Cobalt ore', isWater: false },
  { id: 'coal', index: 52, color: '#2021B7', name: 'Coal', isWater: false },
  { id: 'lignite', index: 53, color: '#657ED6', name: 'Lignite', isWater: false },
  { id: 'peat', index: 54, color: '#25E508', name: 'Peat', isWater: false },
  { id: 'sulfur', index: 55, color: '#459F19', name: 'Sulfur', isWater: false },
  { id: 'saltpeter', index: 56, color: '#EF1756', name: 'Saltpeter', isWater: false },
  { id: 'rock_salt', index: 57, color: '#262811', name: 'Rock salt', isWater: false },
  { id: 'cinnabar', index: 58, color: '#4DCDD8', name: 'Cinnabar', isWater: false },
  { id: 'lodestone', index: 59, color: '#C6FD81', name: 'Lodestone', isWater: false },
  { id: 'alum', index: 60, color: '#1F3023', name: 'Alum', isWater: false },
  { id: 'cotton_boll', index: 61, color: '#3766A2', name: 'Cotton boll', isWater: false },
  { id: 'flax_stem', index: 62, color: '#B03D6C', name: 'Flax stem', isWater: false },
  { id: 'hemp_fiber', index: 63, color: '#AB4C4C', name: 'Hemp fiber', isWater: false },
  { id: 'jute', index: 64, color: '#23691C', name: 'Jute', isWater: false },
  { id: 'sisal', index: 65, color: '#C315A8', name: 'Sisal', isWater: false },
  { id: 'silk_cocoon', index: 66, color: '#43FDC2', name: 'Silk cocoon', isWater: false },
  { id: 'spider_silk', index: 67, color: '#A52690', name: 'Spider silk', isWater: false },
  { id: 'wool_fleece', index: 68, color: '#32EE73', name: 'Wool fleece', isWater: false },
  { id: 'cashmere', index: 69, color: '#55239E', name: 'Cashmere', isWater: false },
  { id: 'alpaca_fleece', index: 70, color: '#D87CCE', name: 'Alpaca fleece', isWater: false },
  { id: 'down_feather', index: 71, color: '#AC9B45', name: 'Down feather', isWater: false },
  { id: 'flight_feather', index: 72, color: '#6CC513', name: 'Flight feather', isWater: false },
  { id: 'animal_hair', index: 73, color: '#0D2766', name: 'Animal hair', isWater: false },
  { id: 'horsehair', index: 74, color: '#65651F', name: 'Horsehair', isWater: false },
  { id: 'straw', index: 75, color: '#C81207', name: 'Straw', isWater: false },
  { id: 'hay', index: 76, color: '#011A80', name: 'Hay', isWater: false },
  { id: 'reed', index: 77, color: '#26CE32', name: 'Reed', isWater: false },
  { id: 'cattail', index: 78, color: '#607106', name: 'Cattail', isWater: false },
  { id: 'vine', index: 79, color: '#28AFCA', name: 'Vine', isWater: false },
  { id: 'kelp', index: 80, color: '#23A07E', name: 'Kelp', isWater: false },
  { id: 'cowhide', index: 81, color: '#69392D', name: 'Cowhide', isWater: false },
  { id: 'pigskin', index: 82, color: '#00B7EB', name: 'Pigskin', isWater: false },
  { id: 'sheepskin', index: 83, color: '#393D38', name: 'Sheepskin', isWater: false },
  { id: 'deerskin', index: 84, color: '#7B1F8B', name: 'Deerskin', isWater: false },
  { id: 'bear_pelt', index: 85, color: '#379F09', name: 'Bear pelt', isWater: false },
  { id: 'wolf_pelt', index: 86, color: '#0ADF2B', name: 'Wolf pelt', isWater: false },
  { id: 'fox_pelt', index: 87, color: '#22E30E', name: 'Fox pelt', isWater: false },
  { id: 'rabbit_pelt', index: 88, color: '#D2A263', name: 'Rabbit pelt', isWater: false },
  { id: 'beaver_pelt', index: 89, color: '#FDAEF8', name: 'Beaver pelt', isWater: false },
  { id: 'seal_skin', index: 90, color: '#875DA0', name: 'Seal skin', isWater: false },
  { id: 'crocodile_scales', index: 91, color: '#8F505F', name: 'Crocodile scales', isWater: false },
  { id: 'snake_skin', index: 92, color: '#16707D', name: 'Snake skin', isWater: false },
  { id: 'fish_scales', index: 93, color: '#85E711', name: 'Fish scales', isWater: false },
  { id: 'turtle_shell', index: 94, color: '#7B626C', name: 'Turtle shell', isWater: false },
  { id: 'snail_shell', index: 95, color: '#3F7839', name: 'Snail shell', isWater: false },
  { id: 'oyster_shell', index: 96, color: '#682BE8', name: 'Oyster shell', isWater: false },
  { id: 'clam_shell', index: 97, color: '#911CC5', name: 'Clam shell', isWater: false },
  { id: 'crab_shell', index: 98, color: '#472B00', name: 'Crab shell', isWater: false },
  { id: 'lobster_carapace', index: 99, color: '#944EF3', name: 'Lobster carapace', isWater: false },
  { id: 'coral', index: 100, color: '#E45411', name: 'Coral', isWater: false },
  { id: 'animal_bone', index: 101, color: '#0AA248', name: 'Animal bone', isWater: false },
  { id: 'animal_skull', index: 102, color: '#378059', name: 'Animal skull', isWater: false },
  { id: 'rib_bone', index: 103, color: '#BAC4D9', name: 'Rib bone', isWater: false },
  { id: 'femur', index: 104, color: '#09FE8B', name: 'Femur', isWater: false },
  { id: 'ivory_tusk', index: 105, color: '#1917D0', name: 'Ivory tusk', isWater: false },
  { id: 'boar_tusk', index: 106, color: '#056E1B', name: 'Boar tusk', isWater: false },
  { id: 'deer_antler', index: 107, color: '#90D624', name: 'Deer antler', isWater: false },
  { id: 'moose_antler', index: 108, color: '#96D013', name: 'Moose antler', isWater: false },
  { id: 'bull_horn', index: 109, color: '#EE6850', name: 'Bull horn', isWater: false },
  { id: 'ram_horn', index: 110, color: '#50F465', name: 'Ram horn', isWater: false },
  { id: 'animal_tooth', index: 111, color: '#4753C4', name: 'Animal tooth', isWater: false },
  { id: 'shark_tooth', index: 112, color: '#9C96AD', name: 'Shark tooth', isWater: false },
  { id: 'bear_claw', index: 113, color: '#31CF2B', name: 'Bear claw', isWater: false },
  { id: 'eagle_talon', index: 114, color: '#007882', name: 'Eagle talon', isWater: false },
  { id: 'porcupine_quill', index: 115, color: '#2113FA', name: 'Porcupine quill', isWater: false },
  { id: 'animal_sinew', index: 116, color: '#367C86', name: 'Animal sinew', isWater: false },
  { id: 'animal_intestine', index: 117, color: '#15AC45', name: 'Animal intestine', isWater: false },
  { id: 'animal_bladder', index: 118, color: '#A62D00', name: 'Animal bladder', isWater: false },
  { id: 'leather_scrap', index: 119, color: '#33B4FA', name: 'Leather scrap', isWater: false },
  { id: 'rawhide', index: 120, color: '#02D94A', name: 'Rawhide', isWater: false },
  { id: 'wild_carrot', index: 121, color: '#F02279', name: 'Wild carrot', isWater: false },
  { id: 'wild_potato', index: 122, color: '#E5151D', name: 'Wild potato', isWater: false },
  { id: 'turnip', index: 123, color: '#FD4E84', name: 'Turnip', isWater: false },
  { id: 'radish', index: 124, color: '#735869', name: 'Radish', isWater: false },
  { id: 'onion_bulb', index: 125, color: '#E70920', name: 'Onion bulb', isWater: false },
  { id: 'garlic_clove', index: 126, color: '#251083', name: 'Garlic clove', isWater: false },
  { id: 'ginger_root', index: 127, color: '#E401DA', name: 'Ginger root', isWater: false },
  { id: 'ginseng_root', index: 128, color: '#DE6A2B', name: 'Ginseng root', isWater: false },
  { id: 'cassava_root', index: 129, color: '#D18714', name: 'Cassava root', isWater: false },
  { id: 'beetroot', index: 130, color: '#D49034', name: 'Beetroot', isWater: false },
  { id: 'blueberry', index: 131, color: '#CABADC', name: 'Blueberry', isWater: false },
  { id: 'blackberry', index: 132, color: '#541697', name: 'Blackberry', isWater: false },
  { id: 'raspberry', index: 133, color: '#5D95AA', name: 'Raspberry', isWater: false },
  { id: 'strawberry', index: 134, color: '#F9BD6F', name: 'Strawberry', isWater: false },
  { id: 'cranberry', index: 135, color: '#B5339A', name: 'Cranberry', isWater: false },
  { id: 'elderberry', index: 136, color: '#92536C', name: 'Elderberry', isWater: false },
  { id: 'juniper_berry', index: 137, color: '#F208AD', name: 'Juniper berry', isWater: false },
  { id: 'apple', index: 138, color: '#C8933A', name: 'Apple', isWater: false },
  { id: 'pear', index: 139, color: '#25E506', name: 'Pear', isWater: false },
  { id: 'peach', index: 140, color: '#96BA51', name: 'Peach', isWater: false },
  { id: 'raw_beef', index: 141, color: '#5E893C', name: 'Raw beef', isWater: false },
  { id: 'raw_pork', index: 142, color: '#650D90', name: 'Raw pork', isWater: false },
  { id: 'raw_mutton', index: 143, color: '#8F051F', name: 'Raw mutton', isWater: false },
  { id: 'venison', index: 144, color: '#F0F088', name: 'Venison', isWater: false },
  { id: 'rabbit_meat', index: 145, color: '#D143F1', name: 'Rabbit meat', isWater: false },
  { id: 'bear_meat', index: 146, color: '#364097', name: 'Bear meat', isWater: false },
  { id: 'raw_poultry', index: 147, color: '#D1C50D', name: 'Raw poultry', isWater: false },
  { id: 'pheasant_meat', index: 148, color: '#1119A3', name: 'Pheasant meat', isWater: false },
  { id: 'duck_meat', index: 149, color: '#AC76B2', name: 'Duck meat', isWater: false },
  { id: 'raw_fish', index: 150, color: '#606B70', name: 'Raw fish', isWater: false },
  { id: 'salmon', index: 151, color: '#2BE28E', name: 'Salmon', isWater: false },
  { id: 'trout', index: 152, color: '#D537F0', name: 'Trout', isWater: false },
  { id: 'cod', index: 153, color: '#010958', name: 'Cod', isWater: false },
  { id: 'eel', index: 154, color: '#010FAC', name: 'Eel', isWater: false },
  { id: 'animal_fat_tallow', index: 155, color: '#789ED7', name: 'Animal fat (Tallow)', isWater: false },
  { id: 'lard', index: 156, color: '#240687', name: 'Lard', isWater: false },
  { id: 'blubber', index: 157, color: '#4570B8', name: 'Blubber', isWater: false },
  { id: 'animal_liver', index: 158, color: '#D3F602', name: 'Animal liver', isWater: false },
  { id: 'animal_heart', index: 159, color: '#997942', name: 'Animal heart', isWater: false },
  { id: 'bird_egg', index: 160, color: '#95983E', name: 'Bird egg', isWater: false },
  { id: 'fresh_water', index: 161, color: '#421F85', name: 'Fresh water', isWater: true },
  { id: 'salt_water', index: 162, color: '#655CED', name: 'Salt water', isWater: true },
  { id: 'rainwater', index: 163, color: '#1BB5E3', name: 'Rainwater', isWater: true },
  { id: 'morning_dew', index: 164, color: '#BB6D9A', name: 'Morning dew', isWater: false },
  { id: 'ice_chunk', index: 165, color: '#AC9878', name: 'Ice chunk', isWater: false },
  { id: 'snowball', index: 166, color: '#13E222', name: 'Snowball', isWater: false },
  { id: 'honeycomb', index: 167, color: '#00649C', name: 'Honeycomb', isWater: false },
  { id: 'raw_honey', index: 168, color: '#CBD923', name: 'Raw honey', isWater: false },
  { id: 'beeswax', index: 169, color: '#7A14FD', name: 'Beeswax', isWater: false },
  { id: 'maple_syrup', index: 170, color: '#8ADE3C', name: 'Maple syrup', isWater: false },
  { id: 'aloe_vera_gel', index: 171, color: '#76F72B', name: 'Aloe vera gel', isWater: false },
  { id: 'natural_rubber', index: 172, color: '#CD89A7', name: 'Natural rubber', isWater: false },
  { id: 'amber', index: 173, color: '#C700C3', name: 'Amber', isWater: false },
  { id: 'tar', index: 174, color: '#014785', name: 'Tar', isWater: false },
  { id: 'pitch', index: 175, color: '#98D320', name: 'Pitch', isWater: false },
  { id: 'animal_blood', index: 176, color: '#484EF6', name: 'Animal blood', isWater: false },
  { id: 'venom_gland', index: 177, color: '#582A8F', name: 'Venom gland', isWater: false },
  { id: 'ink_sac', index: 178, color: '#50147B', name: 'Ink sac', isWater: false },
  { id: 'musk_gland', index: 179, color: '#38C8D2', name: 'Musk gland', isWater: false },
  { id: 'guano', index: 180, color: '#1F2E14', name: 'Guano', isWater: false },
  { id: 'topsoil', index: 181, color: '#559B34', name: 'Topsoil', isWater: false },
  { id: 'potting_soil', index: 182, color: '#FBA7DC', name: 'Potting soil', isWater: false },
  { id: 'peat_moss', index: 183, color: '#5E2B9A', name: 'Peat moss', isWater: false },
  { id: 'river_mud', index: 184, color: '#166788', name: 'River mud', isWater: false },
  { id: 'swamp_muck', index: 185, color: '#0D8770', name: 'Swamp muck', isWater: false },
  { id: 'sand', index: 186, color: '#2734A4', name: 'Sand', isWater: false },
  { id: 'silica_sand', index: 187, color: '#074533', name: 'Silica sand', isWater: false },
  { id: 'red_clay', index: 188, color: '#8BF0B0', name: 'Red clay', isWater: false },
  { id: 'white_clay_kaolin', index: 189, color: '#3A7AD1', name: 'White clay (Kaolin)', isWater: false },
  { id: 'terracotta_clay', index: 190, color: '#81639C', name: 'Terracotta clay', isWater: false },
  { id: 'silt', index: 191, color: '#27527E', name: 'Silt', isWater: false },
  { id: 'loam', index: 192, color: '#24390F', name: 'Loam', isWater: false },
  { id: 'volcanic_ash', index: 193, color: '#3922ED', name: 'Volcanic ash', isWater: false },
  { id: 'charcoal', index: 194, color: '#720A0D', name: 'Charcoal', isWater: false },
  { id: 'wood_ash', index: 195, color: '#5512A3', name: 'Wood ash', isWater: false },
  { id: 'bone_meal', index: 196, color: '#84037F', name: 'Bone meal', isWater: false },
  { id: 'seashell_dust', index: 197, color: '#394011', name: 'Seashell dust', isWater: false },
  { id: 'crushed_quartz', index: 198, color: '#566901', name: 'Crushed quartz', isWater: false },
  { id: 'seaweed', index: 199, color: '#8D349C', name: 'Seaweed', isWater: false },
  { id: 'moss', index: 200, color: '#24AFA2', name: 'Moss', isWater: false },
  { id: 'workbench', index: 201, color: '#8B5A2B', name: 'Workbench', isWater: false }
];

export const BLOCK_MAP = new Map(BLOCKS.map(b => [b.id, b]));
export const BLOCK_BY_INDEX = new Map(BLOCKS.map(b => [b.index, b]));
